"""add AuthUsers model

Revision ID: e99001c60151
Revises: f0381f39cd2b
Create Date: 2022-06-04 23:29:58.214364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99001c60151'
down_revision = 'f0381f39cd2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
