"""add is_valid field

Revision ID: f0381f39cd2b
Revises: 05f38fa4d052
Create Date: 2022-05-22 20:24:34.307867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0381f39cd2b'
down_revision = '05f38fa4d052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_valid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_valid')
    # ### end Alembic commands ###
